smol-rs/fastrand

src/lib.rs

Useful for "splitting" the RNG when passing it down to sub-components/functions.
Note that this internally mutates the Rng to create a clone.
Closes #3

Implement `Clone` for `Rng`

---

src/lib.rs

Creates a generator from a seed. Avoids wasting the thread_local seed when we're going to replace it anyway.

Add `Rng::from` function

---

Cargo.toml
src/lib.rs

Currently this library (and `async-executor`) crashes on wasm due to missing `std::time`. This replaces it with cross-platform library `instant`.
Note that `instant` library could be used by default on all targets, but I added it for `wasm32` only as it cuts dependency count on native targets.

Add wasm support

---

src/lib.rs

See https://github.com/smol-rs/fastrand/issues/15 ,
previously the result would not necessarily be within the range.
The issue is on line 271, because `len` may be negative.
For example, for the range -100 .. 40, we will perform `-100 - -40` which
wraps around to -116.
From that negative number, we need to recover the correct distance
between -100 and 40. Previously, the code to do so was `-116 as u32`. But
that is incorrect since it wraps around `u32::MAX` and gives
4294967180. Instead, what should be done is: `-116 as u8 as u32` to
give the correct distance: 140.
This is what this commit changes. However, it is not a one-line change
since the macro did not have access to the unsigned counterpart for each
signed integer type. So I have added one more parameter to rng_integer!
so that we …

Fix bug when generating a signed integer within a range

---

Cargo.toml
README.md
benches/bench.rs
src/lib.rs

Wyrand is faster than PCG and also passes all of the tests.
PCG benchmarks:
```
test shuffle_fastrand   ... bench:         405 ns/iter (+/- 9)
test u32_fastrand       ... bench:      13,779 ns/iter (+/- 657)
test u8_fastrand        ... bench:      13,771 ns/iter (+/- 696)
```
Wyrand benchmarks:
```
test shuffle_fastrand ... bench:         225 ns/iter (+/- 2)
test u32_fastrand     ... bench:      11,464 ns/iter (+/- 317)
test u8_fastrand      ... bench:      12,402 ns/iter (+/- 304)
```
Closes #19

Switch to Wyrand

---

src/lib.rs
tests/char.rs

This PR provides implementations of `char` for fastrand, together with some tests; closes #24.

added char() implementations and tests

---

benches/bench.rs
src/lib.rs
tests/smoke.rs

Fills a byte slice with random data.
It's too bad there's no generic gen function, but I think in most cases we want to fill byte slices.

Implement `Rng::fill`

---

src/lib.rs

Looking at the fill method, I noticed there was some room for optimisation, and also removing unnecessary `unwrap()` from the hot loop. Also, the remainder portion was generating new entropy blocks for every `u8` portion, when any remaining slice length would always be less than 8 bytes, or one `u64` block (which is what `WyRand` generates per new state), Therefore, a maximum of seven `u8` calls can be reduced to just one `u64` block.
Afterwards, I simplified the copying of entropy to make use of `copy_from_slice`, since we know that either the slices will match (and need no `try_into` conversions), or that the length of the input will always be smaller than the target.
I then benchmarked the resulting code, on my AMD Ryzen 5 Pro 2500U (4C/8T 2,0Ghz base, 3.6Ghz max) with 16GB RAM. …

Optimise .fill() throughput

---

benches/bench.rs
src/lib.rs
tests/smoke.rs

This PR removes interior mutability from the `Rng` type by removing the `Cell` from inside of it and making all of its methods take `&mut`. This closes #31, and also helps with #36 as a side effect, since we can't call `u64()` anymore from `&self`.
This is a breaking change, but resolving most of our current issues would require a breaking change as well.
Closes #26 
Closes #38

Remove interior mutability from Rng

---

src/lib.rs

Closes #36 by adding a `fork()` method that can be used to clone the RNG with a new seed. This strategy is also used in `Rng::new()` to fork from the global RNG.

feat: Add a fork() method

---

.github/workflows/ci.yml
Cargo.toml
src/global_rng.rs
src/lib.rs

This PR adds a feature named `std`. When disabled, the thread-local generator and `Rng::new()` are disabled. This allows `fastrand` to be used in `no_std` environments.

feat: Add no_std mode

---

.github/workflows/ci.yml
Cargo.toml

- Disable dependency on instant when std feature is disabled
- Fix no-std check
Use no-std target to ensure we don't link to std.

Touch up PR 50

---

src/global_rng.rs
src/lib.rs
tests/smoke.rs

This PR adds an iterator selection function, `choice()`, that takes an `ExactSizeIterator` and chooses a random value from it. In addition, I reimplement functions like `alphanumeric()` using `choice()`.
Right now, the API returns `Option<I::Item>`, since an iterator could be empty. However, it may be slightly more idiomatic to have it return `I::Item` and panic if given an empty/buggy iterator.

feat: Add an iterator selection function

---

Cargo.toml
src/global_rng.rs
src/lib.rs

This PR adds an indicator to the `docs.rs` version of `fastrand` indicating when a method is `std`-only. The indicator looks like this:

docs: Add indicators for methods that are std-only

---

Cargo.toml
src/global_rng.rs
src/lib.rs

See [this comment](https://github.com/smol-rs/fastrand/pull/59#issuecomment-1546589997). On Web targets with the `js` feature enabled, the `getrandom` crate is used to seed the global RNG. When it isn't, it just uses a fixed seed.
Closes #27
Closes #54

Use getrandom for seeding the RNG on WASM targets

---

README.md
src/lib.rs

Also, port some bits over from src/lib.rs to README.md

Mention fastrand-contrib in documentation

---

src/global_rng.rs
src/lib.rs

```
error: the item `Vec` is imported redundantly
--> src/lib.rs:119:5
|
119 | use alloc::vec::Vec;
|     ^^^^^^^^^^^^^^^
--> /rustc/5119208fd78a77547c705d1695428c88d6791263/library/std/src/prelude/mod.rs:115:13
|
= note: the item `Vec` is already defined here
|
= note: `-D unused-imports` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(unused_imports)]`
```

Always set #![no_std] to fix redundant import warning

---

src/global_rng.rs

Because the first step of wyrand is an addition with a constant, a non-zero seed is not required

Remove unnecessary seed modifcation

---

src/lib.rs

**BREAKING CHANGE**
This PR introduces updates to `fastrand`'s Wyrand algorithm, primarily using updated constants from the final v4.2 implementation of `wyhash`. This modification of the constants means the output of the generator is different, hence the breaking change. Based on the C reference, the new constants are generated using the same secrets algorithm but with a modification to ensure the constants are also large prime numbers. This additional property has helped improve the quality of the hashing for wyhash and the reference `wyrand` function.
Given the wide usage of `fastrand`, improving the quality of the generated output will be a nice plus, especially if it does not involve any performance hits (since `fastrand` is about being *fast*). But it will necessitate a new major …

Use wyrand final v4.2 constants for gen_u64()

---

src/lib.rs

128-bit targets are apparently not supported by Rust yet, and this is
causing an error to be raised.
Closes #85

Remove 128-bit usize value generator

---

README.md
src/global_rng.rs
src/lib.rs

Accepting only `Iterator`s needlessly constrains the API (case in point, the clunky example with `vec![...].iter()` where a simple array would suffice).
Shouldn't be a breaking change since all `Iterator`s are no-op `IntoIterator`s.

Accept any IntoIterator in choose_multiple

---

Cargo.toml

This fixes the wasm-bindgen-test errors in CI.

Bump resolver to version 2 to fix web CI

---

Cargo.toml

Reverts smol-rs/fastrand#96
See https://github.com/smol-rs/fastrand/pull/95#issuecomment-2524799476

Revert "Bump resolver to version 2 to fix web CI"

---

.github/workflows/ci.yml

See https://github.com/smol-rs/.github/pull/1 for details about reusable workflows.
See https://blog.rust-lang.org/2024/04/09/updates-to-rusts-wasi-targets.html for details about the second commit.

ci: Use reusable workflows for fmt and security_audit & fix CI failure

---

src/lib.rs

This is trivially possible here, enables `Rng` construction in const contexts, and I can't think of any downsides.

Make `Rng::with_seed` const

---

src/global_rng.rs
src/lib.rs
tests/smoke.rs

The previous int-to-float conversion had a bias of probability 2^-24 / 2^-53 for types f32 / f64 respectively. The new conversion has a bias of 2^-64, which is the same bias as the underlying WyRand generator. See comments in `lib.rs` for explanation.
The new conversion is a slightly shorter instruction sequence on x86 and ARM, but executes as 1 more uop on x86. Seems unlikely to harm performance much, if at all. https://rust.godbolt.org/z/q3zMxEc3T.
The added tests in `smoke.rs` fail with the old conversion and succeed with the new conversion.

Improve quality of f32/f64 generation.

---

src/lib.rs

See commit messages for details.

Remove manual doc(cfg(..)) & Fix rustdoc::broken_intra_doc_links warning
